import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { AppSidebar } from "./_components/AppSidebar";
import { getSession } from "@/lib/session";
import { serverFetch } from "@/lib/api";
import { THEME_INIT_SCRIPT } from "@/lib/theme";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await getSession();
  const user = session?.userId ? await serverFetch("/api/auth/me").then((res) => (res.ok ? res.json() : null)) : null;
  const sidebarOpen = (await cookies()).get("sidebar_state")?.value !== "false";

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <body className="min-h-full flex flex-col bg-background text-foreground">
        {user ? (
          <TooltipProvider>
            <SidebarProvider defaultOpen={sidebarOpen}>
              <AppSidebar username={user.username} role={user.role} />
              <SidebarInset>
                <div className="sticky top-0 z-40 flex h-12 items-center gap-2 border-b bg-background/80 px-4 backdrop-blur">
                  <SidebarTrigger />
                </div>
                {children}
              </SidebarInset>
            </SidebarProvider>
          </TooltipProvider>
        ) : (
          <main className="flex-1">{children}</main>
        )}
      </body>
    </html>
  );
}
